name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑 for ${{ matrix.unityVersion }}
    strategy:
      matrix:
        unityVersion:
          - 2021.1.2f1
    runs-on: ubuntu-latest
    container:
      # with linux-il2cpp. image from https://hub.docker.com/r/gableroux/unity3d/tags
      image: unityci/editor:ubuntu-${{ matrix.unityVersion }}-linux-il2cpp-0
    steps:
      # create unity activation file and store to artifacts.
      - name: Create Unity Activation File
        run: /opt/unity/Editor/Unity -quit -batchmode -nographics -logFile -createManualActivationFile || exit 0
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Unity_v${{ matrix.unityVersion }}.alf
          path: ./Unity_v${{ matrix.unityVersion }}.alf
  