name: CI
on:
  pull_request:
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  test:
    name: Test on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.7f1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-${{ hashFiles('**/packages-lock.json') }}
          restore-keys: |
            Library-
      - name: Unity - Test Runner
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: ${{ matrix.unityVersion }}
